### ISSUE TITLE
Find-first function flawed

### ISSUE THREAD

**Issue by sebastian-king** [untrobotics/website#10]
The find-first-available-officer telephony function needs to support multiple callers. Currently it checks if anyone is queued at all, but it should instead check if the calling SID is still in the queue. Otherwise, with two users in the queue the script will continue to run even when the intended caller has been de-queued.

**Comment by sebastian-king** [comment]
Implemented in 00d4fedab20e8c6d2465afab0c28c425d05176e3 but not tested.

**Comment by ntindle** [comment]
How would you like to test this. 

Also need to update new officers

**Comment by sebastian-king** [comment]
Yes, we should update and test it at our next officer meeting
