### ISSUE TITLE
Write docs for dyndns service

### ISSUE THREAD

**Issue by sebastian-king** [untrobotics/website#12]
Should we force dyndns assigned names to be on a subdomain lower than dyndns.untrobotics.com? @ntindle

**Comment by ntindle** [comment]
If in the form name.dyndns.untrobotics.com, yes

Nicholas Tindle

________________________________

**Comment by sebastian-king** [comment]
I agree, I've just realised people could overwrite things like sasl.untrobotics.com otherwise.
