### ISSUE TITLE
Replace Discord Join with GroupMe Join

### ISSUE THREAD

**Issue by sebastian-king** [untrobotics/website#26]
Replace Discord Join with GroupMe Join

**Comment by TylerAdamMartinez** [comment]
https://groupme.com/join_group/48461300/sfmmOwpm 
^^^ That's the general chat link

**Comment by TylerAdamMartinez** [comment]
![logo-groupme](https://user-images.githubusercontent.com/57375362/73598244-4d256d80-44fb-11ea-88ca-6c872d609ffd.png)

**Comment by TylerAdamMartinez** [comment]
@sebastian-king  I don't believe the /join directory is in the repo, yet

**Comment by sebastian-king** [comment]
The `/join` is a virtual path created in the .htaccess file. The files are actually in `/auth/`
