### ISSUE TITLE
Update our-team bio information

### ISSUE THREAD

**Issue by sebastian-king** [untrobotics/website#31]
To do:

- Katie Lee need to have a professional photo, no snapchat filters please.
- Fergie, Katie, Michelle, Andrew and Noel require "about me" text.
- Tyler's photo needs to be made square.
- Nicole's photo is way too dark and also not square.
- Michelle needs a professional photo, not a selfie please.
- Tyler's GitHub link should be in the middle.
- Possibly a new picture of Alex? The photo looks quite distorted.
- A header photo needs to be created (@sebastian-king needs to do this)
- Double check photo compression and what's in the `full` folder (@sebastian-king)

**Comment by TylerAdamMartinez** [comment]
@sebastian-king I don't believe many of the mechies are active on GitHub; therefore, I will relay the information onto them if you have not already.

**Comment by TylerAdamMartinez** [comment]
I also in the office in NTDaily rn, so I'll do my best to edit the photos of the officers that we have rn

**Comment by sebastian-king** [comment]
Awesome, thanks. You don't need to make a pull request for those, you can just email them to me

**Comment by TylerAdamMartinez** [comment]
Well, ... I just did #/ 
Oops

**Comment by sebastian-king** [comment]
#33 sort-of merged? lol

Still waiting for photos from:
@MASSIVE-SUCCESS 
@MichelleVRV 

Still waiting for bios from:
@MASSIVE-SUCCESS 
@MichelleVRV 
@skriptbitkitty

**Comment by TylerAdamMartinez** [comment]
@sebastian-king ikr

Ask about it during the meeting, tonight!

**Comment by sebastian-king** [comment]
Done.
