### ISSUE TITLE
Get Involved text is the wrong colour (it's white on white)

### ISSUE THREAD

**Issue by sebastian-king** [untrobotics/website#32]
The Get Involved heading on the homepage is invisible, because ti is the wrong colour (it's white on white).

See here: https://github.com/untrobotics/website/blob/bca9ed0f9cbf1785c6b809a89facaff040e0510d/index.php#L35

**Comment by sebastian-king** [comment]
File `../images/home-02-1920x1005.jpg` is missing from the server.

**Comment by ntindle** [comment]
Can we fix the file names to be more representative of what they are

**Comment by sebastian-king** [comment]
Yes... that's why I deleted it. I looked at the file and assumed it wasn't important.

**Comment by sebastian-king** [comment]
Fixed in production. Will link commit and close this when pushed.

**Comment by sebastian-king** [comment]
Merged in #36
