### ISSUE TITLE
Format T-shirt  sizes and colors better on mobile 

### ISSUE THREAD

**Issue by ntindle** [untrobotics/website#34]
![9BB4E832-AD28-4789-B10B-FA69692EB3C8](https://user-images.githubusercontent.com/8845353/73906800-c9a4ad00-4869-11ea-9024-eedbef9d3ac1.png)

**Comment by sebastian-king** [comment]
Do you just mean the columns should wrap? A margin at the top of the shirts probably wouldn’t go amiss either.

**Comment by sebastian-king** [comment]
The T-shirt page has been overhauled. Closing this issue.
